### PR TITLE
Switch license to GPL v3.0

### PR DESCRIPTION
**Pull request by ldesgoui**
To previous contributors:

Hello,

Your code has made it in this repository, and I'd like to switch the license to be GPL v3.0 to abide with SourceMod's licensing requirements, I'm asking for your approval:

- [x] @ldesgoui 
- [x] @kingofings 
- [x] @bodolaz146 
- [x] @sapphonie
- [x] @laurirasanen

Thank you

### CODE REVIEW

**Comment by ldesgoui** [comment]
Closes #64

**Comment by kingofings** [comment]
Fine with me :ok_hand:

**Comment by sapphonie** [comment]
👍

**Comment by laurirasanen** [comment]
looks good to me

**Comment by bodolaz146** [comment]
Fine with me

**Pull request merged**
